name: semantic_versioning

on:
  push:

jobs:
  release:
    runs-on:  ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          
      - name: Create Release 
        id: release
        uses: ncipollo/release-action@v1.14.0
        with:
          generateReleaseNotes: true
          name: ${{ steps.semver.outputs.next }}
          tag: ${{ steps.semver.outputs.next }}
          token: ${{ secrets.GITHUB_TOKEN }}
